apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-deploy
  namespace: python-app
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: micro
  template:
    metadata:
      labels:
        app: micro
    spec:
      containers:
      - name: micro-cont
        image: 277707120669.dkr.ecr.eu-west-1.amazonaws.com/python-img:latest
        ports:
        - containerPort: 5000

